language: java
sudo: false
dist: trusty

before_script:
- unset -v _JAVA_OPTIONS
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
   - stage: Graal
    env: JDK=graalvm-ce-19.2.1
    script: source install-jdk.sh --url https://github.com/oracle/graal/releases/download/vm-19.2.1/graalvm-ce-linux-amd64-19.2.1.tar.gz

script:
  mvn package -Pnative -Dnative-image.docker-build=true
  
notifications:
  email:
    on_success: never
    on_failure: always
